#!/bin/sh
(
cd /home/deconti/Workspace/DFCI-CCCB-Plexwell-pipeline/cromwell-executions/PlexwellProcessing/ce778bb3-d9c4-4da0-868b-33a82ee5d435/call-write_foo_map/execution
cat /home/deconti/Workspace/DFCI-CCCB-Plexwell-pipeline/cromwell-executions/PlexwellProcessing/ce778bb3-d9c4-4da0-868b-33a82ee5d435/call-write_foo_map/inputs/home/deconti/Workspace/DFCI-CCCB-Plexwell-pipeline/cromwell-executions/PlexwellProcessing/ce778bb3-d9c4-4da0-868b-33a82ee5d435/call-test_map/shard-0/execution/A.txt /home/deconti/Workspace/DFCI-CCCB-Plexwell-pipeline/cromwell-executions/PlexwellProcessing/ce778bb3-d9c4-4da0-868b-33a82ee5d435/call-write_foo_map/inputs/home/deconti/Workspace/DFCI-CCCB-Plexwell-pipeline/cromwell-executions/PlexwellProcessing/ce778bb3-d9c4-4da0-868b-33a82ee5d435/call-test_map/shard-1/execution/B.txt /home/deconti/Workspace/DFCI-CCCB-Plexwell-pipeline/cromwell-executions/PlexwellProcessing/ce778bb3-d9c4-4da0-868b-33a82ee5d435/call-write_foo_map/inputs/home/deconti/Workspace/DFCI-CCCB-Plexwell-pipeline/cromwell-executions/PlexwellProcessing/ce778bb3-d9c4-4da0-868b-33a82ee5d435/call-test_map/shard-2/execution/C.txt > output.tsv
)
echo $? > /home/deconti/Workspace/DFCI-CCCB-Plexwell-pipeline/cromwell-executions/PlexwellProcessing/ce778bb3-d9c4-4da0-868b-33a82ee5d435/call-write_foo_map/execution/rc.tmp
(
cd /home/deconti/Workspace/DFCI-CCCB-Plexwell-pipeline/cromwell-executions/PlexwellProcessing/ce778bb3-d9c4-4da0-868b-33a82ee5d435/call-write_foo_map/execution

)
mv /home/deconti/Workspace/DFCI-CCCB-Plexwell-pipeline/cromwell-executions/PlexwellProcessing/ce778bb3-d9c4-4da0-868b-33a82ee5d435/call-write_foo_map/execution/rc.tmp /home/deconti/Workspace/DFCI-CCCB-Plexwell-pipeline/cromwell-executions/PlexwellProcessing/ce778bb3-d9c4-4da0-868b-33a82ee5d435/call-write_foo_map/execution/rc
